development: &default
  adapter: postgresql
  encoding: unicode
  database: notekeeper_development
  pool: 5
  username: notekeeper
  password:
  host: db

test:
  <<: *default
  database: notekeeper_test

production:
  <<: *default
  database: notekeeper
  password: ''
